export const categoryList = [
  {
    id: 1,
    value: 'r',
    label: 'Ready to Move',
  },
  {
    id: 2,
    value: 'u',
    label: 'Under Construction',
  },
];
export const options = [
  { value: 'Godrej Woods', label: 'Godrej Woods' },
  { value: 'Ambience tiverton', label: 'Ambience tiverton' },
  { value: 'Godrej Nurture', label: 'Godrej Nurture' },
  { value: 'Ivy County', label: 'Ivy County' },
  { value: 'County 107', label: 'County 107' },
  { value: 'Kalpataru', label: 'Kalpataru' },
  { value: 'Elite GOdrej', label: 'Elite GOdrej' },
  { value: 'World Tower', label: 'World Tower' },
  { value: 'Jaquar', label: 'Jaquar' },
  { value: 'Mercedes', label: 'Mercedes' },
  { value: 'Parx Laurate', label: 'Parx Laurate' },
  
];
export const ratingList = [
  {
    id: 1,
    value: '2',
    label: '2 BHK',
  },
  {
    id: 2,
    value: '3',
    label: '3 BHK',
  },
  {
    id: 3,
    value: '4',
    label: '4 BHK',
  },
  {
    id: 4,
    value: '5',
    label: '5 BHK',
  },
  {
    id: 5,
    value: '6',
    label: 'Penthouse',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'Godrej Woods',
    serviceTime: '2023',
    deliveryFee: 3.44,
    category: 'r',
    cuisine: 'american',
    rating: 5,
    price: 0.7 ,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"











  },
  {
    id: 2,
    title: 'Godrej Nurture',
    serviceTime: '2023',
    deliveryFee: 4.94,
    category: 'r',
    cuisine: 'italian',
    rating: 4,
    price: 0.9,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
   SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 3,
    title: 'Ambience tiverton',
    serviceTime: '2023',
    deliveryFee: 4.94,
    category: 'u',
    cuisine: 'chinese',
    rating: 3,
    price: 1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
 SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 4,
    title: 'Ivy County',
    serviceTime: '2023',
    deliveryFee: 2.14,
    category: 'u',
    cuisine: 'american',
    rating: 1,
    price: 1.5,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 5,
    title: 'County 107',
    serviceTime: '2023',
    deliveryFee: 6.79,
    category: 'r',
    cuisine: 'italian',
    rating: 5,
    price: 2,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 6,
    title: 'Tata Eureka Park',
    serviceTime: '2023',
    deliveryFee: 2.87,
    category: 'u',
    cuisine: 'chinese',
    rating: 5,
    price: 2.5,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 7,
    title: 'Kalpataru',
    serviceTime: '2023',
    deliveryFee: 8.5,
    category: 'r',
    cuisine: 'american',
    rating: 2,
    price: 3,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 8,
    title: 'Gulshan Dynasty',
    serviceTime: '2023',
    deliveryFee: 1.8,
    category: 'u',
    cuisine: 'italian',
    rating: 1,
    price: 4,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
   SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 9,
    title: 'Parx Laurate',
    serviceTime: '2023',
    deliveryFee: 3.33,
    category: 'r',
    cuisine: 'chinese',
    rating: 4,
    price: 4.5,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
   SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 10,
    title: 'Elite good Greens',
    serviceTime: '2023',
    deliveryFee: 1.9,
    category: 'u',
    cuisine: 'american',
    rating: 2,
    price: 4.3,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 11,
    title: 'kalpataru',
    serviceTime: '2023',
    deliveryFee: 4.1,
    category: 'r',
    cuisine: 'italian',
    rating: 3,
    price: 3.3,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
 SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 12,
    title: 'Elite',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'u',
    cuisine: 'chinese',
    rating: 3,
    price: 4.1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 13,
    title: 'Elite GOdrej',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'r',
    cuisine: 'chinese',
    rating: 2,
    price:3.1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
   SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 14,
    title: 'Woods',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'r',
    cuisine: 'chinese',
    rating: 4,
    price: 2.4,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 15,
    title: 'Elite',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'u',
    cuisine: 'chinese',
    rating: 3,
    price: 1.6,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 16,
    title: 'Jaquar',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'r',
    cuisine: 'chinese',
    rating: 3,
    price:0.8,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
   SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 17,
    title: 'Ferrari',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'r',
    cuisine: 'chinese',
    rating: 3,
    price: 3.3,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 18,
    title: 'Mercedes',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'r',
    cuisine: 'chinese',
    rating: 3,
    price: 5,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 19,
    title: 'BMW',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'r',
    cuisine: 'chinese',
    rating: 3,
    price: 4.1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 20,
    title: 'Panache',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'u',
    cuisine: 'chinese',
    rating: 3,
    price: 2.1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 21,
    title: 'World Tower',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'r',
    cuisine: 'chinese',
    rating: 3,
    price: 1.1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 22,
    title: 'Elite',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'r',
    cuisine: 'chinese',
    rating: 3,
    price: 4.1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 23,
    title: 'France',
    serviceTime: '24-30min',
    deliveryFee: 1.5,
    category: 'u',
    cuisine: 'chinese',
    rating: 4,
    price: 3.2,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 24,
    title: 'Royal',
    serviceTime: '2023',
    deliveryFee: 1.5,
    category: 'r',
    cuisine: 'chinese',
    rating: 5,
    price: 2.1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
     SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  }, {
    id: 25,
    title: 'Godrej Woods',
    serviceTime: '2023',
    deliveryFee: 3.44,
    category: 'r',
    cuisine: 'american',
    rating: 3,
    price: 0.7 ,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"

  },

  {id: 26,
    title: 'Godrej Woods',
    serviceTime: '2023',
    deliveryFee: 3.44,
    category: 'r',
    cuisine: 'american',
    rating: 4,
    price: 0.7 ,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"

  },
  {id: 27,
    title: 'Godrej Woods',
    serviceTime: '2023',
    deliveryFee: 3.44,
    category: 'r',
    cuisine: 'american',
    rating: 2,
    price: 0.7 ,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"

  },
  {
    id: 28,
    title: 'Godrej Nurture',
    serviceTime: '2023',
    deliveryFee: 4.94,
    category: 'r',
    cuisine: 'italian',
    rating: 2,
    price: 0.9,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
   SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  }, {
    id: 29,
    title: 'Godrej Nurture',
    serviceTime: '2023',
    deliveryFee: 4.94,
    category: 'r',
    cuisine: 'italian',
    rating: 3,
    price: 0.9,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
   SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  }, {
    id: 30,
    title: 'Godrej Nurture',
    serviceTime: '2023',
    deliveryFee: 4.94,
    category: 'r',
    cuisine: 'italian',
    rating: 4,
    price: 0.9,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
   SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 31,
    title: 'Godrej Nurture',
    serviceTime: '2023',
    deliveryFee: 4.94,
    category: 'r',
    cuisine: 'italian',
    rating: 5,
    price: 0.9,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
   SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 32,
    title: 'Ambience tiverton',
    serviceTime: '2023',
    deliveryFee: 4.94,
    category: 'u',
    cuisine: 'chinese',
    rating: 2,
    price: 1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
 SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 33,
    title: 'Ambience tiverton',
    serviceTime: '2023',
    deliveryFee: 4.94,
    category: 'u',
    cuisine: 'chinese',
    rating: 3,
    price: 1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
 SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 34,
    title: 'Ambience tiverton',
    serviceTime: '2023',
    deliveryFee: 4.94,
    category: 'u',
    cuisine: 'chinese',
    rating: 4,
    price: 1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
 SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 35,
    title: 'Ambience tiverton',
    serviceTime: '2023',
    deliveryFee: 4.94,
    category: 'u',
    cuisine: 'chinese',
    rating: 5,
    price: 1,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
 SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
  {
    id: 36,
    title: 'Ivy County',
    serviceTime: '2023',
    deliveryFee: 2.14,
    category: 'u',
    cuisine: 'american',
    rating: 2,
    price: 1.5,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 37,
    title: 'Ivy County',
    serviceTime: '2023',
    deliveryFee: 2.14,
    category: 'u',
    cuisine: 'american',
    rating: 3,
    price: 1.5,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },{
    id: 38,
    title: 'Ivy County',
    serviceTime: '2023',
    deliveryFee: 2.14,
    category: 'u',
    cuisine: 'american',
    rating: 4,
    price: 1.5,
    coverSrc: 'https://i.imgur.com/AxHdH0n.jpg',
    SuperArea:"1000sqft",
    CarpetArea:"1200sqft",
    NoofBalconies:"4",
    Loading:"500",
    Electricload:"2kw",
    Powerbackup:"yes",
    FurnishedorSemifernished:"Semi",
    CeilingHeight:"15ft",
    MainDoorHeight:"12ft",
    InternalDoorHeights:"7ft"
  },
];
